const { DataTypes } = require("sequelize");
const { sequelize } = require("../config/db");

const Wishlist = sequelize.define("Wishlist", {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  }
  // userId added via associations
});

// A join table for Wishlist <-> Product is auto-generated by Sequelize belongsToMany,
// but we just define the base Wishlist here.

module.exports = Wishlist;
